### ISSUE TITLE
Sync code editor with active question

### ISSUE THREAD

**Issue by VladislavPetyukevich** [sorface/interview-platform#202]
Update code editor value and content in room state when switch active question in room.

Also send ws events:
```
Type: "CodeEditor",
Value: {AdditionalData: { value: boolean }}
```
```
Type: "ChangeCodeEditor"
Value: "string" // empty string when question doesnt have code editor
```

**Comment by blowin** [comment]
@VladislavPetyukevich Now when querying Room/{id}/state instead of CodeEditorContent there will be an object of 2 fields, the object itself will always be filled (cannot be null), and inside the optional property “Content” and there is a sign whether the code editor is enabled “Enabled” (cannot be null).

**Comment by blowin** [comment]
@VladislavPetyukevich 
Added “room-code-editor-enabled” event, now you should use it to update the code editor. Example request:
{
	“Type": ‘room-code-editor-enabled’,
	“Value“: ‘{\’Enabled\”: false }”
}

This event is available for 2 different types:
- Expert
- Examinee

![Image](https://github.com/user-attachments/assets/8941a9d1-c115-4d05-a012-29772aa607d8)
